### ISSUE TITLE
ParallelPersistor concurrent statements

### ISSUE THREAD

**Issue by ilya-khorev** [Abc-Arbitrage/cassandra-drivers-benchmark#1]
Hi

Maybe I'm wrong but it seems like the maximum number of simultaneous queries limits by asyncWorkersCount, rather than by maximumInFlightStatements. 

Within each task queries are executed one by one because task awaits a result of the query and resumes only when the result is returned. 
Each task can handle only one query at once therefore maximumInFlightStatements param is redundant.

**Comment by alprema** [comment]
You are indeed correct, I will fix it soon and update my measurements (you are welcome to make a PR if you feel like it though).

Thank you for your suggestion.

**Comment by ilya-khorev** [comment]
Sorry in advance, I'm not an expert in threads, task and so on. But could you please clarify why do you launch cassandra calls in several longrunning task? Is there a disadvantage of doing like this (since calls are mostly IO bound rather than CPU bound):

```
Task.Factory.StartNew(async () =>
            {
                while (true)
                {
                    await m_QueriesInFlightSemaphore.WaitAsync();
                    Task.Run(async () =>
                    {
                        PendingInsert pendingInsert = null;
                        try
                        {
                            pendingInsert = await m_InsertionQueue.ReceiveAsync();

                            RowSet rowSet = await m_Session.ExecuteAsync(pendingInsert.Statement);

                            pendingInsert.Completion.SetResult(rowSet);
                        }
                        catch (InvalidOperationException) 
                        {
                            m_Log.Info("Received stop signal");
                        }
                        catch (Exception ex)
                        {
                            m_Log.Error(ex);
                            pendingInsert?.Completion.SetException(ex);
                        }
                        finally
                        {
                            m_QueriesInFlightSemaphore.Release();
                            m_QueriesWaitingInLineSemaphore.Release();
                        }
                    });
                }
            }, TaskCreationOptions.LongRunning);
```

Besides that, I'm not pretty sure (probably, it's somewhere in my code, but anyway), when I'm trying to execute RequestsRunner.Insert from different threads, it stucks somewhere.

**Comment by alprema** [comment]
The main purpose is to avoid creating millions of tasks, and have the corresponding GCs slowing you down.
